"""
Example usages of climate_year_selection_tool.

Run from this folder (climate_year_selection_tool/) after generating the data:
    python examples/make_synthetic_data.py
    python examples/all_example_usages.py

Or from anywhere:
    PYTHONPATH=climate_year_selection_tool/src python examples/example_usage.py
"""
# %%

import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

# Add src/ to the path so the package is importable without installation
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from climate_year_selection_tool import add_custom_year, save_result, select_years

# ─────────────────────────────────────────────────────────────────────────────
# Setup: define data file, variables, seasons
# ─────────────────────────────────────────────────────────────────────────────

# Path of source data file (this one is generated by make_synthetic_data.py)
DATA_FILE = Path(__file__).parent.parent / "data" / "synthetic_climate_data.csv"
# Variables to include in the scoring, i.e. on which variate the selected years should be representative. Must be columns in df.
VARIABLES = ["temp", "wind", "solar"]
# Define seasons for seasonal scoring
SEASONS = {"Winter": [10, 11, 12, 1, 2, 3], "Summer": [4, 5, 6, 7, 8, 9]}

# ── load ─────────────────────────────────────────────────────────────────────
df = pd.read_csv(DATA_FILE, parse_dates=["Date"])

# Results folder: results/all_example_usages/<timestamp>/
RESULTS_DIR = (
    Path(__file__).parent.parent
    / "results"
    / "all_example_usages"
    / datetime.now().strftime("%Y%m%d_%H%M%S")
)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)



# %%
# ─────────────────────────────────────────────────────────────────────────────
# 1. Single-model, calendar year, seasonal Wasserstein (default)
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 1. Single-model, calendar year ===")

df["year"] = df["Date"].dt.year

result = select_years(
    df,
    variables=VARIABLES,
    n_select=5,
    year_col="year",
    scoring="seasonal_wasserstein",  # default
    seasons=SEASONS,
    n_experiments=5,
    cooling_rate=0.8,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected {result.year_col}s : {result.selected}")
print(f"Best score     : {result.score:.6f}")
print(f"Log rows       : {len(result.log_df)}")
print(f"Num experiments: {len(result.all_runs)}")
print(f"All scores     : {[round(r['score'], 6) for r in result.all_runs]}")

save_result(
    result,
    "exp1",
    {
        "n_select": 5,
        "scoring": "seasonal_wasserstein",
        "n_experiments": 5,
        "cooling_rate": 0.8,
        "max_iter": 2_000,
        "random_state": 42,
        "year_col": "year",
    },
    RESULTS_DIR,
)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 2. Single-model, hydrological year starting April 1
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 2. Single-model, hydrological year (April start) ===")

df = add_custom_year(df, date_col="Date", start_month=4, year_col_name="hydro_year")

result_hydro = select_years(
    df,
    variables=VARIABLES,
    n_select=5,
    year_col="hydro_year",
    seasons=SEASONS,
    n_experiments=5,
    cooling_rate=0.9,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected {result_hydro.year_col}s : {result_hydro.selected}")
print(f"Best score     : {result_hydro.score:.6f}")

save_result(
    result_hydro,
    "exp2",
    {
        "n_select": 5,
        "scoring": "seasonal_wasserstein",
        "n_experiments": 5,
        "cooling_rate": 0.9,
        "max_iter": 2_000,
        "random_state": 42,
        "year_col": "hydro_year",
    },
    RESULTS_DIR,
)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 3. Non-seasonal (annual) Wasserstein scoring
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 3. Annual Wasserstein scoring ===")

result_annual = select_years(
    df,
    variables=VARIABLES,
    n_select=5,
    year_col="year",
    scoring="wasserstein",
    n_experiments=5,
    cooling_rate=0.8,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected {result_annual.year_col}s : {result_annual.selected}")
print(f"Best score     : {result_annual.score:.6f}")

save_result(
    result_annual,
    "exp3",
    {
        "n_select": 5,
        "scoring": "wasserstein",
        "n_experiments": 5,
        "cooling_rate": 0.8,
        "max_iter": 2_000,
        "random_state": 42,
        "year_col": "year",
    },
    RESULTS_DIR,
)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 4. Multi-model: stack two copies of the dataset with different model labels
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 4. Multi-model ===")

df_a = df.assign(model="model_a")
df_b = df.assign(model="model_b")
df_multi = pd.concat([df_a, df_b], ignore_index=True)

result_multi = select_years(
    df_multi,
    variables=VARIABLES,
    n_select=5,
    year_col="year",
    model_col="model",
    n_experiments=5,
    cooling_rate=0.8,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected (model, year): {result_multi.selected}")
print(f"Best score            : {result_multi.score:.6f}")

save_result(
    result_multi,
    "exp4",
    {
        "n_select": 5,
        "scoring": "seasonal_wasserstein",
        "n_experiments": 5,
        "cooling_rate": 0.8,
        "max_iter": 2_000,
        "random_state": 42,
        "year_col": "year",
        "model_col": "model",
    },
    RESULTS_DIR,
)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 5. Inspect the SA convergence log of the best run
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 5. Convergence log of best run ===")

log = result.log_df
print(log.columns.tolist())
print(log[["iter", "temp", "score_best", "acc_rate"]].tail(5).to_string(index=False))

save_result(
    result,
    "exp5",
    {
        "n_select": 5,
        "scoring": "seasonal_wasserstein",
        "n_experiments": 5,
        "cooling_rate": 0.8,
        "max_iter": 2_000,
        "random_state": 42,
        "year_col": "year",
        "note": "convergence_log_inspection",
    },
    RESULTS_DIR,
)
