"""
Fast example usage of climate_year_selection_tool.

Run from this folder (climate_year_selection_tool/) after generating the data:
    python examples/make_synthetic_data.py
    python examples/fast_example_usage.py

Or from anywhere:
    PYTHONPATH=climate_year_selection_tool/src python examples/fast_example_usage.py
"""
# %%

import sys
from pathlib import Path

import pandas as pd

# Add src/ to the path so the package is importable without installation
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from climate_year_selection_tool import add_custom_year, select_years

# ─────────────────────────────────────────────────────────────────────────────
# Setup: define data file, variables, seasons
# ─────────────────────────────────────────────────────────────────────────────

# Path of source data file (this one is generated by make_synthetic_data.py)
DATA_FILE = Path(__file__).parent.parent / "data" / "synthetic_climate_data.csv"
# Variables to include in the scoring, i.e. on which variate the selected years should be representative. Must be columns in df.
VARIABLES = ["temp", "wind", "solar"]
# Define seasons for seasonal scoring
SEASONS = {"Winter": [10, 11, 12, 1, 2, 3], "Summer": [4, 5, 6, 7, 8, 9]}

# ── load ─────────────────────────────────────────────────────────────────────
df = pd.read_csv(DATA_FILE, parse_dates=["Date"])

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 1. Single-model, calendar year, seasonal Wasserstein (default)
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 1. Single-model, calendar year ===")

df["year"] = df["Date"].dt.year

result = select_years(
    df,
    variables=VARIABLES,
    n_select=5,
    year_col="year",
    scoring="seasonal_wasserstein",  # default
    seasons=SEASONS,
    n_experiments=5,
    cooling_rate=0.8,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected years : {result.selected}")
print(f"Best score     : {result.score:.6f}")
print(f"Log rows       : {len(result.log_df)}")
print(f"Num experiments: {len(result.all_runs)}")
print(f"All scores     : {[round(r['score'], 6) for r in result.all_runs]}")

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 2. Single-model, hydrological year starting April 1
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 2. Single-model, hydrological year (April start) ===")

df = add_custom_year(df, date_col="Date", start_month=4, year_col_name="hydro_year")

result_hydro = select_years(
    df,
    variables=VARIABLES,
    n_select=5,
    year_col="hydro_year",
    seasons=SEASONS,
    n_experiments=5,
    cooling_rate=0.9,
    max_iter=2_000,
    random_state=42,
)

print(f"Selected years : {result_hydro.selected}")
print(f"Best score     : {result_hydro.score:.6f}")

# %%
# ─────────────────────────────────────────────────────────────────────────────
# 3. Inspect the SA convergence log of the best run
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== 3. Convergence log of best run ===")

log = result.log_df
print(log.columns.tolist())
print(log[["iter", "temp", "score_best", "acc_rate"]].tail(5).to_string(index=False))
